### ISSUE TITLE
kratos: mail languages and redirects

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1907]
> The first verification email is in the correct language. When you ask for another email in auth/verification it goes in German.
(by @hugotiburtino)

**Comment by elbotho** [comment]
can reproduce
Also I get redirected to the german instance even If I click on the link in the first mail (the english one).

**Comment by elbotho** [comment]
My guess would be that `de.{domain}` is hardcoded somewhere. Did not find it in the cf-worker. 
@hugotiburtino could you check kratos?

**Comment by elbotho** [comment]
Exactly the same behaviour on the recovery mail:
- mail in german 
- link forwards to `de.serlo-staging.dev/auth/…` even if I manually add a `en` into the link in the mail

**Comment by hugotiburtino** [comment]
> Also I get redirected to the german instance even If I click on the link in the first mail (the english one).

The following happens:
The [link](https://github.com/serlo/infrastructure-modules-shared/blob/main/kratos/values.yaml#L62) is set to the generic `serlo-staging.dev` (for the reasons for that see [here](https://github.com/ory/kratos/discussions/2667)). So, when you click the link, your browser redirects you to ~your locale,  in our case~ _de_. We can't dynamically set the base_url of the link. 

So, we have the following options:
~a. We do a hack in the [gotmpl](https://github.com/serlo/frontend/blob/kratos/src/data/en/index.ts#L1044): get the link and change it to v.g. `https://en.{{ .VerificationURL }}`.~

~b. We remove the custom base_url of the link. That would call our public kratos url directly, which is supposed to redirect us to the original serlo url. It caused a problem back then, when you are developing in localhost, but anyway it is not better for localhost now.~

*Important*: I will documentate that, but you need to change the link from v.g. `https://serlo-staging.dev/api/.ory/self-service/verification...` to `http://localhost:3000/api/.ory/self-service/verification...`  to make it work locally. If we remove the custom base url the link will be v.g. . `https://kratos.serlo-staging.dev/self-service/verification...` and you need to change it manually anyway.

c. We live with that for now and in the near future we use code, not a magic link. It was already integrated into Kratos main branch, we would have to adapt our UI only.

edit: see another option in comment below

**Comment by hugotiburtino** [comment]
> The first verification email is in the correct language. When you ask for another email in auth/verification it goes in German.

I have taken a look at the database. 
Indeed, the trait language is  not even set, v.g. ` {"email": "hugo+test8@...", "username": "hugotest8"}`
But somehow I've managed to do it once:
`{"email": "hugo+test2@...", "language": "en", "username": "hugotest2"}`

@elbotho Is it possible that the `lang` of `useInstanceData()` comes as `undefined` somehow?

**Comment by elbotho** [comment]
>a. We do a hack in the [gotmpl](https://github.com/serlo/frontend/blob/kratos/src/data/en/index.ts#L1044): get the link and change it to v.g. https://en.{{ .VerificationURL }}.

That would be nice but as I said earlier adding `en.` to the URLs before accessing them did not change the behaviour for me.

**Comment by elbotho** [comment]
> @elbotho Is it possible that the lang of useInstanceData() comes as undefined somehow?

~Where in the code?~
I just checked to make sure: On the registering page when submitting `lang` is set.
So if [this line](https://github.com/serlo/frontend/blob/kratos/src/components/pages/auth/registration.tsx#L45) still works it should end up in the db.

**Comment by elbotho** [comment]
```
csrf_token: "…"
method: "password"
password : "…"
traits.email: "botho+test@serlo.org"
traits.language: "de"
traits.username: "bothoTest"
```
Those are the values provided to `submitSelfServiceRegistrationFlow`

**Comment by hugotiburtino** [comment]
Sorry for the unnecessary investigations. The mistake was made in post registration hook in api. Solved in https://github.com/serlo/api.serlo.org/pull/694/commits/fff00cc11f1a337b4e94c5f51b4aaf3a9dc976c4. And the identities that had language trait happened when the hook failed. And it makes a lot of sense now why the first email was in the correct language (since it is sent before calling the hook).

It is quite disapointing to see the hook failing like that, but we don't have any choice besides waiting for https://github.com/ory/kratos/pull/2343 or even better completing the phase 2 of the user migration in the near future (i.e. not needing the hook anymore. Anyway it would be a follow-up).

**Comment by elbotho** [comment]
> Sorry for the unnecessary investigations. 

No worries, great find. Did you test it already? Is the redirect now the only bug remaining here?

**Comment by hugotiburtino** [comment]
> That would be nice but as I said earlier adding en. to the URLs before accessing them did not change the behaviour for me.

You are right, sorry.
[Here](https://github.com/serlo/infrastructure-modules-shared/blob/main/kratos/values.yaml#L79) is the reason why you get redirected to the domain (not subdomain), ~which redirects you to the subdomain corresponding to your locale.~
A simple way of fixing it would be to append a query parameter `return_to` (it has to be allowed in the kratos config).
To be honest, I don't think it worths to be fixed now.

**Comment by hugotiburtino** [comment]
> Did you test it already?   

yes it works.

> Is the redirect now the only bug remaining here?

@elbotho I've answered it in the last comment

**Comment by elbotho** [comment]
> To be honest, I don't think it worths to be fixed now.

It would make registering pretty cumbersome for other instances, right?
I'll think about it tomorrow.


> yes it works.

Nice 🎉 can confirm. language is correct now.

When clicking on the link in the mail I get a 403 right now, can you repoduce?

**Comment by hugotiburtino** [comment]
> It would make registering pretty cumbersome for other instances, right?

~I suppose the normal flow would be something like the following: you are in Mexico and you get automatically redirected to _es.serlo.org_. You make the registration and you get redirected to _es.serlo.org_ again. So, no problem.
(We could test it using a VPN if you have any...)~

~The only problem would be something like the following scenario: you live in Germany, but you actually want to use the English instance. You open serlo.org but you get redirected to _de.serlo.org_, you are maybe already lost, but after some struggling you find a way to go to _en.serlo.org_. After you register, you get back to _de.serlo.org_.~

You are right. Only solution I see now is to use return_to query parameter and even that may be buggy. We could try to use code instead of magic link, but developing it would be a micro-feature, so it is better to do it as follow-up.

**Comment by hugotiburtino** [comment]
> When clicking on the link in the mail I get a 403 right now, can you repoduce?

I can't. Maybe you tested while I was playing with the deployment... Could you test again?

**Comment by hugotiburtino** [comment]
I found the following problem ~with the mismatch between instance (subdomain) and user location~: when recovering the account, you get a lot of errors in the console (it can be very cpu consuming). 

I think a follow-up would be to use code, instead of magic link.

**Comment by hugotiburtino** [comment]
Ok, I have to give in: I just suppose that the user is redirected to the instance according to the locale, because it makes sense, but I'm not sure...

edit: it seems to be hardcoded: serlo.org redirects you directly to de.serlo.org 😞  forget everything I said earlier about it

**Comment by elbotho** [comment]
following @hugotiburtino's idea this is now solved in the frontend.

a82279f3076f1c4181b67a7208c95bcd1d40c9a2
c320ff6d48aeae9546eafc877d7bd10570dd28b3
02cb4c76eee9a535b25884b7dcbc1bf4aa01e2d3
1161157e9b1788bdd362e627d9efdef3cde7ad40

Seems to work. Feel free to reopen if you encounter problems.
