### ISSUE TITLE
Missing entry in taxonomy

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#417]
On this page: http://localhost:3000/mathe/deutschland/bayern/gymnasium/jahrgangsstufentest-8.-klasse---bmt-8

The old design contains the folder 2019, but this is missing in the new frontend. The API request is also showing no entry for it.

**Comment by Entkenntnis** [comment]
@inyono Maybe this is caching related?

**Comment by inyono** [comment]
Already tracked: https://github.com/serlo/serlo.org/issues/465

**Comment by Entkenntnis** [comment]
fixed in serlo.org

**Comment by inyono** [comment]
Still not live, though. But yeah, will get deployed in the upcoming days.
